// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseEnv } from './env';

const SUPABASE_URL = supabaseEnv.url;
const SUPABASE_PUBLISHABLE_KEY = supabaseEnv.publishableKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabaseEnv };

if (supabaseEnv.isMisconfigured) {
  // Keep this loud: when env vars are wrong, the app can accidentally point back
  // to the old Lovable/Enaitoti project and show their data.
  console.error('[4ON4] Supabase misconfiguration:', supabaseEnv.misconfigurationReason);
}

const createMisconfiguredClient = (): SupabaseClient<Database> => {
  const reason = supabaseEnv.misconfigurationReason || 'Supabase misconfigured';
  return new Proxy(
    {},
    {
      get() {
        throw new Error(
          `[4ON4] ${reason}. Set VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY in Netlify and redeploy.`
        );
      },
    }
  ) as unknown as SupabaseClient<Database>;
};

export const supabase: SupabaseClient<Database> = supabaseEnv.isMisconfigured
  ? createMisconfiguredClient()
  : createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });